# Generated by Django 5.1.2 on 2024-10-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_election_end_time_alter_election_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='votes_cast',
            field=models.IntegerField(default=0),
        ),
    ]
