# Generated by Django 5.1.4 on 2025-01-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0004_election_votes_cast"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ElectionResults",
        ),
    ]
