# Generated by Django 5.1.2 on 2024-10-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_voter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='number_of_winners',
            field=models.IntegerField(default=1),
        ),
    ]
