# Generated by Django 5.1.2 on 2024-10-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_ballot_number_of_winners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='votes_cast',
        ),
    ]
