# Generated by Django 5.1.2 on 2024-10-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_ballot_votes_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
