# Generated by Django 5.1.2 on 2024-10-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_voter_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
    ]
