# Generated by Django 5.1.4 on 2025-01-21 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0004_election_votes_cast"),
        ("voting", "0006_remove_vote_verified_remove_vote_voter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blockchain_Vote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockchain_vote",
                        to="elections.election",
                    ),
                ),
            ],
        ),
    ]
