# Generated by Django 5.1.4 on 2025-01-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0007_blockchain_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockchain_vote",
            name="vote_data",
            field=models.JSONField(default={}),
        ),
    ]
