# Generated by Django 5.1.4 on 2025-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0008_blockchain_vote_vote_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockchain_vote",
            name="status",
            field=models.CharField(
                choices=[
                    ("complete", "COMPLETE"),
                    ("in_progress", "IN_PROGRESS"),
                    ("failed", "FAILED"),
                ],
                default="in_progress",
            ),
        ),
        migrations.AlterField(
            model_name="blockchain_vote",
            name="vote_data",
            field=models.JSONField(default=dict),
        ),
    ]
