# Generated by Django 5.1.4 on 2025-01-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0012_remove_ballot_results_published_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ballot",
            name="description",
        ),
    ]
